### ISSUE TITLE
timestamps(public?: true) returns with ForbiddenField

### ISSUE THREAD

**Issue by sezaru** [traveltechdeluxe/ash-rbac#32]
If I create a resource with `timestamps(public?: true)` and have some rbac rule with `fields :*` for an action, both fields with return as `ForbiddenField`:

```elixir
  inserted_at: #Ash.ForbiddenField<field: :inserted_at, type: :attribute, ...>,
  updated_at: #Ash.ForbiddenField<field: :updated_at, type: :attribute, ...>,
```

If I change to `timestamps(public?: false)` , for whatever reason it starts returning correctly again.

**Comment by barnabasJ** [comment]
I'll have to check if we maybe run our transformer before the timestamps are turned into attributes

**Comment by barnabasJ** [comment]
Something changed with a newer version of Ash. I have a test that reproduced the issue. I'll try to fix it this week.
